/**
 * @File Name          : TestClass.cls
 * @Description        : Testing the VScode
 * @Author             : Sai
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 8/8/2019, 8:58:08 PM
 * @Modification Log   : 
 *==============================================================================
 * Ver         Date                     Author      		      Modification
 *==============================================================================
 * 1.0    8/8/2019, 8:57:33 PM   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/
public with sharing class TestClass {
    Public list<Customer__c> cust;
    public TestClass() {
 }
}